
def base_roi_keywords():
    search_keywords = [
        ["Rt", "superior", "frontal", "gyrus"],
        ["Lt", "superior", "frontal", "gyrus"],
        ["Rt", "middle", "frontal", "gyrus"],
        ["Lt", "middle", "frontal", "gyrus"],
        ["Rt", "inferior", "frontal", "gyrus"],
        ["Lt", "inferior", "frontal", "gyrus"],
        ["Rt", "precentral"],
        ["Lt", "precentral"],
        ["Rt", "postcentral"],
        ["Lt", "postcentral"],
        ["Rt", "inferior", "parietal"],
        ["Lt", "inferior", "parietal"],
        ["Rt", "superior", "parietal"],
        ["Lt", "superior", "parietal"],
        ["Rt", "orbital"],
        ["Lt", "orbital"],
        ["Rt", "paracentral"],
        ["Lt", "paracentral"],
        ["Rt", "precuneus"],
        ["Lt", "precuneus"],
        ["Rt", "thalamus"],
        ["Lt", "thalamus"],
        ["Rt", "insular"],
        ["Lt", "insular"],
        ["Rt", "medioventral", "occipital"],
        ["Lt", "medioventral", "occipital"],
        ["Rt", "lateral", "occipital"],
        ["Lt", "lateral", "occipital"],
        ["Rt", "cerebellum"],
        ["Lt", "cerebellum"],
        ["Rt", "substantia", "nigra"],
        ["Lt", "substantia", "nigra"],
        ["Rt", "red", "nucleus"],
        ["Lt", "red", "nucleus"],
        ["Rt", "fusiform"],
        ["Lt", "fusiform"],
        ["Rt", "precuneus"],
        ["Lt", "precuneus"],
        ["Rt", "cingulate"],
        ["Lt", "cingulate"],
        ["Rt", "parahippocampal"],
        ["Lt", "parahippocampal"],
        ["Rt", "amygdala"],
        ["Lt", "amygdala"],
        ["Rt", "hippocampus"],
        ["Lt", "hippocampus"],
        ["Rt", "basal", "ganglia"],
        ["Lt", "basal", "ganglia"],
        ["Hypothalamus"],
        ["Rt" , "substantia", "nigra"],
        ["Lt" , "substantia", "nigra"],
        ["Brainstem"],
    ]

    return search_keywords
